
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Apr 06 23:36:51 CEST 2015
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STOP = 23;
  public static final int AND = 17;
  public static final int IDENT = 27;
  public static final int TESIS = 6;
  public static final int OR = 18;
  public static final int ENDIF = 26;
  public static final int THEN = 25;
  public static final int PAREN = 5;
  public static final int LOCAL = 13;
  public static final int NOT = 19;
  public static final int END = 8;
  public static final int IF = 24;
  public static final int CLOG = 28;
  public static final int WITH = 21;
  public static final int BEGIN = 7;
  public static final int STATE_MACHINE = 2;
  public static final int CONDITION = 22;
  public static final int COMA = 3;
  public static final int EOF = 0;
  public static final int BEHAVIOUR = 16;
  public static final int INPUTS = 12;
  public static final int FINAL = 11;
  public static final int error = 1;
  public static final int STATES = 10;
  public static final int START = 20;
  public static final int PC = 4;
  public static final int OUTPUTS = 14;
  public static final int ASIG = 9;
  public static final int TRANSITION = 15;
}

